# Generated by Django 3.1.3 on 2020-11-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
